<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\Social\Tests\Migration;

use OCA\Social\Migration\Version1000Date20221118000002;
use OCP\IAppConfig;
use PHPUnit\Framework\TestCase;

/**
 * That the squashed schema is still the schema the history produced.
 *
 * `Version1000Date20221118000002` replaces the sixty-seven migrations that
 * built this app's tables between November 2022 and September 2026. It was
 * generated by replaying them against {@see FakeSchema}, never written by
 * hand, and the two were identical in every table, column, type, option, index
 * and key before the originals were removed.
 *
 * `schema.json` is that replay's output, captured in the commit that did the
 * squash. Checking out this commit's parent and replaying `lib/Migration`
 * there reproduces it exactly, which is what makes it evidence rather than a
 * list somebody typed. From here on it is the fixed point: a change to the
 * squash that was not meant to change the schema fails against it.
 *
 * A mistake here does not fail on a branch. It fails on a stranger's `occ
 * upgrade`, against their data.
 *
 * What is not checked here is what the DDL becomes on each platform — that is
 * the real DBAL's business, and the integration suite's.
 */
class SquashedSchemaTest extends TestCase {
	/**
	 * The last moment the squash describes: 21 September 2026, when it was
	 * written. A step dated after this was never subsumed by it.
	 */
	private const SQUASHED_THROUGH = '20260921000000';

	/** @return array<string, object> the one dependency any step is constructed with */
	private function stand(): array {
		return [IAppConfig::class => $this->createStub(IAppConfig::class)];
	}

	/** @return array<string, array{columns: array, indexes: array, primary: array}> */
	private function recorded(): array {
		return json_decode((string)file_get_contents(__DIR__ . '/schema.json'), true);
	}

	private function squashed(): FakeSchema {
		return MigrationReplay::run([Version1000Date20221118000002::class], $this->stand());
	}

	public function testItDescribesTheSchemaTheHistoryProduced(): void {
		$this->assertSame(
			$this->recorded(),
			$this->squashed()->shape(),
			'the squashed migration no longer describes the schema the sixty-seven produced'
		);
	}

	/**
	 * Run twice, it asks for nothing the second time.
	 *
	 * This is the property that lets one file serve a database that is empty, a
	 * database that is half upgraded and a database that is already current:
	 * every step is guarded, so a second pass finds everything present and does
	 * nothing. It is why there is no floor on the version an instance may
	 * upgrade from, and an unguarded `addColumn` would break that — on a real
	 * database, where it throws, rather than here.
	 */
	public function testEveryStepIsGuarded(): void {
		$schema = $this->squashed();
		$once = $schema->shape();

		MigrationReplay::run([Version1000Date20221118000002::class], $this->stand(), $schema);

		$this->assertSame($once, $schema->shape(), 'running it a second time changed the schema');
	}

	/**
	 * It has to run before everything else, because everything else needs its
	 * tables. Nextcloud runs migrations in version order and that order is the
	 * class name, so the name is a sort key: `20221118000002` puts this first,
	 * immediately after the original initial step it subsumes.
	 */
	public function testItRunsBeforeEveryStepThatIsLeft(): void {
		$steps = MigrationReplay::steps();

		$this->assertSame(Version1000Date20221118000002::class, $steps[0]);
	}

	/**
	 * Of the steps the squash subsumed, the ones left beside it move data.
	 *
	 * A schema can be squashed because it is a description of an end state. A
	 * backfill cannot: it reads rows and rewrites them, and whether it has run
	 * is not visible in the shape of the table it ran against. So a step that
	 * only shapes tables belonged in the squash, and one that touches rows
	 * could not.
	 *
	 * **Only of the steps it subsumed.** The squash is already recorded as run
	 * on every instance that has ever upgraded — it carries the version of the
	 * initial step it replaced — so Nextcloud never runs it again there. A
	 * table added to it would exist on fresh installs and on nobody else's
	 * server. Anything written after it therefore needs a file of its own,
	 * schema-only or not, and this rule stops at the cut-off rather than
	 * forbidding every new table for ever.
	 */
	public function testOnlyTheStepsThatMoveDataAreLeftBesideIt(): void {
		foreach (MigrationReplay::steps([Version1000Date20221118000002::class]) as $class) {
			$name = substr($class, strrpos($class, '\\') + 1);
			if ($this->writtenAfterTheSquash($name)) {
				continue;
			}

			$source = (string)file_get_contents(dirname(__DIR__, 2) . '/lib/Migration/' . $name . '.php');

			$this->assertMatchesRegularExpression(
				'/function (pre|post)SchemaChange\([^)]*\)[^{]*\{\s*(?!\s*\})/',
				$source,
				$name . ' only shapes tables, so it belongs in the squash rather than beside it'
			);
		}
	}

	/**
	 * Whether a step is newer than the squash, and so is not one it subsumed.
	 *
	 * The squash's own name is a sort key rather than a date; this is the day
	 * it was actually written, which is the line between what it replaced and
	 * what came after.
	 */
	private function writtenAfterTheSquash(string $name): bool {
		return preg_match('/Date(\d{14})$/', $name, $matches) === 1
			&& $matches[1] > self::SQUASHED_THROUGH;
	}
}
